### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by biplovbhandari** [Pujan789556/BrickKiln#10] opened 2015-01-19 04:30 UTC
When after looking the info for a particular brick kiln and zooming out. At about 10,000 km scale , the application stopped working. We can specify the max Bound for the map and also the minimum and maximum zoom level.

**Comment by nirabpudasaini** [comment] 2015-01-19 05:33
The app crashes on high zoom levels , the zoom button is disabled but user can still pinch out to zoom. There are errors in Clusterer helper functions, here is the stack trace.


01-19 11:13:02.917    4006-4050/map.kll.org.brickkilnnew E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #2
    Process: map.kll.org.brickkilnnew, PID: 4006
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.IllegalArgumentException: invalid pixelY coordinate 1536: -190.02277934669792
            at org.mapsforge.core.util.MercatorProjection.pixelYToLatitude(MercatorProjection.java:448)
            at org.mapsforge.map.util.MapViewProjection.fromPixels(MapViewProjection.java:61)
            at map.kll.org.brickkilnnew.cluster.ClusterManager.getCurBounds(ClusterManager.java:251)
            at map.kll.org.brickkilnnew.cluster.ClusterManager.isItemInViewport(ClusterManager.java:234)
            at map.kll.org.brickkilnnew.cluster.ClusterManager.addItem(ClusterManager.java:172)
            at map.kll.org.brickkilnnew.cluster.ClusterManager.addLeftItems(ClusterManager.java:271)
            at map.kll.org.brickkilnnew.cluster.ClusterManager$ClusterTask.doInBackground(ClusterManager.java:339)
            at map.kll.org.brickkilnnew.cluster.ClusterManager$ClusterTask.doInBackground(ClusterManager.java:321)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by Pujan789556** [comment] 2015-01-28 10:53
Resolved by Nirab

**Closed by Pujan789556** 2015-01-28 10:53 UTC
